# nginx version 1.10
FROM nginx:1.19.8

# เป็นคำสั่งสำหรับการ add config nginx จากเครื่องเข้าไปใน container นะครับ
     # host         # container    
ADD ./default.conf /etc/nginx/conf.d/default.conf